### ISSUE TITLE
Add documentation/examples on how to overwrite background and enable transparency

### ISSUE THREAD

**Issue by git-girl** [catppuccin/tmux#84]
hey firstly thanks for more catppuccin :sunflower: 

i was trying to setup the plugin and wanted to have it have a transparent background. without the plugin in the `tmux.conf` and with the `set-option -g status-style bg=default` it works fine. but once i add the plugin the status bar has a black background. 

i also tried putting the `set-option status-style` before and after the plugin load, and the different versions of the option (allthough the one in the config is the correct one for v3.3a that i'm on).  i also tried settting the alacritty TERM var to `xterm-256color` as described in [the tmux faq](https://github.com/tmux/tmux/wiki/FAQ) 

did i miss an option i have to set for this?

<details>
<summary>this is my tmux.conf</summary>

``` conf
set -g @plugin 'tmux-plugins/tpm'
# actually pretty minimal https://github.com/tmux-plugins/tmux-sensible
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'sainnhe/tmux-fzf'
# yank on y
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'catppuccin/tmux'

set -g mouse on

set -g base-index 1
set -g pane-base-index 1 
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# from https://github.com/aserowy/tmux.nvim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }

bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'
# end https://github.com/aserowy/tmux.nvim

set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_window_default_fill "all"
set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session user host"

# Vi Mode on Prefix v
bind 'v' copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# set-option -sa terminal-overrides ",xterm*:Tc"

# Open panes in pwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Transparent bar and at top
# TODO: this isn't working atm
# this is beacuse of the catppuccin theme somehow
set-option -g status-style bg=default
# set-option -g status-right-style "bg=yellow, fg=black"
set-option -g status-position top

# Prefix
# WARN: this conflicts with my shell comletion binding
unbind C-b
set -g prefix C-space
bind C-Space send-prefix

run '~/.tmux/plugins/tpm/tpm'
```

</details> 

<details>

<summary>screen shot of tmux in alacritty</summary>

![2023-09-14-183914_1920x1048_scrot](https://github.com/catppuccin/tmux/assets/103335462/e41fe69c-d25b-456a-89f6-30934cb88784)

</details>

best regards  :wave:

**Comment by romancsandleriksen** [comment]
I have/had a similar issue
this added to my tmux.conf after setting the theme worked for setting another background color, but I did not check about transparency, maybe there is a line in there as well

set status-bg "#000000"

i found the line in the catppuccin.tmux and changed the value

**Comment by git-girl** [comment]
> I have/had a similar issue this added to my tmux.conf after setting the theme worked for setting another background color
> 
> set status-bg "#000000"
> 
> i found the line in the catppuccin.tmux and changed the value, but I did not check about transparency, maybe there is a line in there as well

thanks @roman-c-e but unfortunately this didn't work for me :/

**Comment by jdrupal-dev** [comment]
What is the status on this?

**Comment by irigyano** [comment]
> > I have/had a similar issue this added to my tmux.conf after setting the theme worked for setting another background color
> > set status-bg "#000000"
> > i found the line in the catppuccin.tmux and changed the value, but I did not check about transparency, maybe there is a line in there as well
> 
> thanks @roman-c-e but unfortunately this didn't work for me :/

Hello, I found the solution for tmux **3.2a**, according to this stackoverflow [answer](https://stackoverflow.com/a/67093003):

> status-fg and status-bg are now applied before status-style rather than instead of; this means that if either is set to default the status-style colour will be used. To fix, replace status-bg default with status-style bg=default.

by putting these two lines  after `run '~/.tmux/plugins/tpm/tpm'` in tmux.conf

`set -g status-bg default`
`set -g status-style bg=default`

What we do here is first overwriting status-bg provided by catppuccin plugin, then status-style setting should be working now,

hope this helps!

**Comment by jdrupal-dev** [comment]
Thanks. I can get it to work by manually editing the catppuccin plugin.
I think it's because I use https://github.com/gpakosz/.tmux and they have a custom way of loading tpm.

**Comment by jdrupal-dev** [comment]
How can I make the background of the left and right section transparent?
![image](https://github.com/catppuccin/tmux/assets/13871894/847fc18b-8c78-4795-9b30-055dc1ab19e4)

**Comment by Will-Hendrix** [comment]
I tried all of the suggested lines in the mentioned [stackoverflow answer](https://stackoverflow.com/a/67093003), but none of them removed the bar. I'm just looking to have it match the purple background; but even when I change the rgb value `thm_bg` of `catppuccin-mocha.tmuxtheme`, it only vaguely gets close rather than using the exact rgb value
![image](https://github.com/catppuccin/tmux/assets/66498307/5a9ec3b3-4a6a-47e8-a8a8-65b04abac129)

**Comment by Will-Hendrix** [comment]
> For me what worked was [this](https://github.com/lpnh/tmux-catppuccin/commit/2dcb01c2b70802209117eb3e4368a8fc9be40636)

making the edit there didn't fix it for me
![image showing change made](https://github.com/catppuccin/tmux/assets/66498307/22d2ed80-0578-4c38-a1f1-4dea29b17303)

**Comment by migueltc13** [comment]
> How can I make the background of the left and right section transparent? ![image](https://private-user-images.githubusercontent.com/13871894/280655632-847fc18b-8c78-4795-9b30-055dc1ab19e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjQ0NDksIm5iZiI6MTcwMjE2NDE0OSwicGF0aCI6Ii8xMzg3MTg5NC8yODA2NTU2MzItODQ3ZmMxOGItOGM3OC00Nzk1LTliMzAtMDU1ZGMxYWIxOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIzMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMjk2MzE2Zjk0YzgxMGRjODBmNmFlMDc4ZTI0ODQxMzI3ZTRjN2ZhNzU3ZDcwMDE4ZDNmMjY1NTBhMmQyMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mADr9kmLhTvubvxCPBYQNeuBTBO-s_wiuKJdhJw70hI)

Hello I got it:

![Screenshot from 2023-12-10 02-23-05](https://github.com/catppuccin/tmux/assets/73550106/5956f215-0ed9-4db7-8f68-dab922bf7ad5)

Here's the code [catppuccin-tmux](https://github.com/migueltc13/catppuccin-tmux/)

**Comment by jdrupal-dev** [comment]
@migueltc13 I tried installing your fork, which made things a bit better, but I still have issues.

<img width="1728" alt="image" src="https://github.com/catppuccin/tmux/assets/13871894/627c24a2-6902-4539-8f10-8addded4d336">

**Comment by migueltc13** [comment]
> @migueltc13 I tried installing your fork, which made things a bit better, but I still have issues.
> 
> 
> 
> <img width="1728" alt="image" src="https://github.com/catppuccin/tmux/assets/13871894/627c24a2-6902-4539-8f10-8addded4d336">
> 
> 
> 
> These are my settings:
> 
> ```
> 
> # catppuccin configs
> 
> set -g @catppuccin_window_left_separator ""
> 
> set -g @catppuccin_window_right_separator " "
> 
> set -g @catppuccin_window_middle_separator " █"
> 
> set -g @catppuccin_window_number_position "right"
> 
> 
> 
> set -g @catppuccin_window_default_fill "number"
> 
> set -g @catppuccin_window_default_text "#W"
> 
> 
> 
> set -g @catppuccin_window_current_fill "number"
> 
> set -g @catppuccin_window_current_text "#W"
> 
> 
> 
> set -g @catppuccin_status_modules "session user date_time"
> 
> set -g @catppuccin_status_left_separator  " "
> 
> set -g @catppuccin_status_right_separator ""
> 
> set -g @catppuccin_status_right_separator_inverse "no"
> 
> set -g @catppuccin_status_fill "icon"
> 
> set -g @catppuccin_status_connect_separator "no"
> 
> 
> 
> set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"
> 
> 
> 
> set -g @catppuccin_directory_text "#{pane_current_path}"
> 
> 
> 
> set -g status-bg default
> 
> set -g status-style bg=default
> 
> ```
> 
> 

You need to add this lines before tpm plugin call:

```
set -g status-bg default
set -g status-style bg=default
```

This will fix most of background

**Comment by jdrupal-dev** [comment]
> I think it's because I use https://github.com/gpakosz/.tmux and they have a custom way of loading tpm.

Thanks, but it still doesn't work. I think this is why.

**Comment by jdrupal-dev** [comment]
I just tried rewriting my entire config.
This is all I have.

```
source-file ~/.config/tmux/tmux.reset.conf
set-option -g default-terminal 'screen-254color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

set -g status-bg default
set -g status-style bg=default

# bind-key -r B run-shell "~/.config/tmux/scripts/sessionizer.sh ~/.config"

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
# set -g @plugin 'omerxx/catppuccin-tmux' # My fork that holds the meetings script bc I'm lazy af
set -g @plugin 'migueltc13/catppuccin-tmux'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 'o'
set -g @sessionx-x-path '~/.config'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @catppuccin_flavour 'macchiato'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory meetings date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_meetings_text "#($HOME/.config/tmux/scripts/cal.sh)"
set -g @catppuccin_date_time_text "%H:%M"

# bootstrap tpm
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run '~/.tmux/plugins/tpm/tpm'
```


<img width="741" alt="image" src="https://github.com/catppuccin/tmux/assets/13871894/8961f0be-24a9-4d3a-bccd-44dafc6716bc">

**Comment by migueltc13** [comment]
This works on mine machine with no issues, whats your tmux version? I'm running `tmux 3.2a`

**Comment by jdrupal-dev** [comment]
I'm running tmux 3.3a, will try to downgrade.

**Comment by jdrupal-dev** [comment]
I just tested on tmux 3.2a, same result.

**Comment by jdrupal-dev** [comment]
@migueltc13 I reinstalled tmux and ran tmux kill-server, and now the transparent background is working!
Thank you for the fix.

**Comment by indesperate** [comment]
@migueltc13 Thanks a lot for the fix, it works pretty fine, btw, I also change the "$thm_grep" to "$thm_bg" in "[window](https://github.com/migueltc13/catppuccin-tmux/tree/main/window)
/window_default_format.sh" to fix the color unconsistence when working with mulit-windows.

**Comment by migueltc13** [comment]
> @migueltc13 Thanks a lot for the fix, it works pretty fine, btw, I also change the "$thm_grep" to "$thm_bg" in "[window_default_format.sh](https://github.com/migueltc13/catppuccin-tmux/tree/main/window/window_default_format.sh)" to fix the color unconsistence when working with mulit-windows.

Thank you!

**Comment by skela** [comment]
did you guys ever get it to work with tmux version 3.3a? haven't been able to find a workaround at all. the closest I've got to is using @migueltc13 's fork,  and it only seems to work for the right most and non-current window tabs - the left most session indicator and the current window tab, have a blue background colour behind it. Same thing happens in both kitty and wezterm.

![2024-01-09-214431_hyprshot](https://github.com/catppuccin/tmux/assets/58268/769d0444-d391-4c57-bf29-8dea8866f9dc)

![2024-01-09-214505_hyprshot](https://github.com/catppuccin/tmux/assets/58268/94041c00-954e-4d99-86c8-298a55cfbccb)

**Comment by skela** [comment]
ah figured it out, this line here did the trick for tmux 3.3a:
![2024-01-09-231338_hyprshot](https://github.com/catppuccin/tmux/assets/58268/a01ede50-c4fb-4bcf-b27e-335bdea0ec99)

`setw window-status-current-style fg=default,bg=default`

**Comment by migueltc13** [comment]
Feel free to make it in my repo and I'll accept it asap

**Comment by skela** [comment]
sure, will do

**Comment by skela** [comment]
@migueltc13  - https://github.com/migueltc13/catppuccin-tmux/pull/1

**Comment by migueltc13** [comment]
Merged, thank you @skela!

**Comment by sgoudham** [comment]
Reading through the thread, unsure how much is relevant to Catppuccin. 

It seems obvious that it's somewhat difficult to overwrite the background and/or set a transparent background. I'll repurpose this issue as a tracker to add documentation/examples on how to do this.

We'd greatly appreciate a PR to the README for this!
